apiVersion: apps/v1
kind: Deployment

metadata:
  name: prediction-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: prediction-api

  template:

    metadata:
      labels:
        app: prediction-api

    spec:

      containers:

      - name: prediction-api

        image: bigdata-ml-api:latest

        # imagePullPolicy: Never
        imagePullPolicy: IfNotPresent

        ports:
          - containerPort: 8000

        command:
          [
            "uvicorn",
            "api.prediction_api:app",
            "--host",
            "0.0.0.0",
            "--port",
            "8000"
          ]